// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCIXUXwHVEM1t3MYUYxh6NQaLKMUKnvSnw',
    appId: '1:314535516074:web:b4be6b30febf872aaabdd3',
    messagingSenderId: '314535516074',
    projectId: 'gawee-app-befcc',
    authDomain: 'gawee-app-befcc.firebaseapp.com',
    storageBucket: 'gawee-app-befcc.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA16DCLQN2rBhxYhUjTjy7igFHr_J8ROhk',
    appId: '1:314535516074:android:dbfa02b75b0e54d7aabdd3',
    messagingSenderId: '314535516074',
    projectId: 'gawee-app-befcc',
    storageBucket: 'gawee-app-befcc.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCIXUXwHVEM1t3MYUYxh6NQaLKMUKnvSnw',
    appId: '1:314535516074:web:33b22855c51f3932aabdd3',
    messagingSenderId: '314535516074',
    projectId: 'gawee-app-befcc',
    authDomain: 'gawee-app-befcc.firebaseapp.com',
    storageBucket: 'gawee-app-befcc.firebasestorage.app',
  );
}
